name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tag (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 更改 Node.js 版本为 18

      - name: Install dependencies with Yarn
        run: yarn install  # 使用 yarn 安装依赖

      - name: Build Electron application using electron-builder
        run: npm run build  # 使用 electron-builder 构建

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOME_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: List contents of the build directory
        run: dir ./dist/

      - name: Upload ZIP to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOME_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/WebToExe-win32-x64/WebToExe.zip  # Corrected path
          asset_name: WebToExe.zip
          asset_content_type: application/zip